name: match_model
channels:
  - nrel
  - conda-forge
  - defaults
dependencies:
  - cloudpickle         # BSD-3-Clause license
  - glpk                # GNU GPL license
  - ipykernel           # BSD-3-Clause license
  - ipython             # BSD License
  - nbconvert           # BSD-3-Clause license
  - nbformat            # BSD-3-Clause license
  - nrel-pysam>=3.0.1   # BSD-3-Clause license
  - nrel-pysam-stubs    # BSD-3-Clause license
  - numpy               # BSD-3-Clause license
  - openpyxl            # MIT license
  - pandas              # BSD-3-Clause license
  - pint                # BSD license
  - plotly              # MIT license
  - pyomo>=6.0.0,<=6.4.0       # BSD license
  - python>=2.7.12      # Python Software Foundation License
  - pytz                # MIT license
  - pyutilib>=6.0.0     # GNU AGPLv3 license
  - requests            # Apache 2.0 license
  - xlrd                # BSD license